name: Deploy to Firebase Hosting

on:
  push:
    branches: [ master, main ]
  pull_request:
    branches: [ master, main ]

jobs:
  build_and_deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Install Firebase CLI
        run: npm install -g firebase-tools

      - name: Deploy to Firebase Hosting and Firestore indexes
        run: firebase deploy --only hosting,firestore:indexes --token ${{ secrets.FIREBASE_TOKEN }} --non-interactive
